### ISSUE TITLE
Support for PHP 8.2

### ISSUE THREAD

**Issue by acelaya** [mezzio/mezzio-swoole#103]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

I'm creating this as I don't see a ticket to add support for php 8.2

I'm willing to contribute the change if needed.

**Comment by gsteel** [comment]
Please do contribute a patch @acelaya if you have the time :)

**Comment by Ocramius** [comment]
@gsteel I suggested contributors may open issues for missing bits: helps us tracking progress 👍

**Comment by acelaya** [comment]
Looks like we need a new release on https://github.com/weierophinney/laminas-ci-swoole-builder 😅 

![Captura desde 2022-10-20 19-56-30](https://user-images.githubusercontent.com/2719332/197023127-bf4ea564-3748-4501-948a-278c037911b6.png)

`https://github.com/weierophinney/laminas-ci-swoole-builder/releases/download/0.2.0/php8.2-swoole.tgz`

**Comment by Ocramius** [comment]
@acelaya issue there please :P

**Comment by acelaya** [comment]
Done https://github.com/weierophinney/laminas-ci-swoole-builder/issues/2

**Comment by acelaya** [comment]
After merging the PR on laminas-ci-swoole-builder repo, now this error is thrown:

```
E: Unable to locate package php8.2-inotify
E: Couldn't find any package by glob 'php8.2-inotify'
```

I need to investigate this one a bit further.

**Comment by Ocramius** [comment]
Seen https://github.com/mezzio/mezzio-swoole/pull/105 ?

**Comment by acelaya** [comment]
Ah, no. Thanks for the heads-up 😅
