### ISSUE TITLE
SwooleStream is cutting down response

### ISSUE THREAD

**Issue by codercms** [mezzio/mezzio-swoole#15]
### Bug Report

SwooleStream is cutting down response when there is one character left in the stream.

Branch: master
#### Summary
```php
// add this test case to the SwooleStreamTest

public function testCrossCase(): void
{
    $len = strlen(self::DEFAULT_CONTENT);

    $this->assertSame('This is a test', $this->stream->read($len - 1));
    $this->assertFalse($this->stream->eof()); // it fails here
}
```
#### Current behavior
Test fails

#### How to reproduce
Just run provided test case

#### Expected behavior
$this->stream->eof() shoud return false, because there is one character left in the stream

**Comment by codercms** [comment]
P.S. You can find the fix here - https://github.com/makise-co/framework/pull/45/files

**Comment by weierophinney** [comment]
@codercms Would you be willing to submit a PR here with the test you've written above, and the fix?

**Comment by codercms** [comment]
@weierophinney sure, check it out https://github.com/mezzio/mezzio-swoole/pull/16

**Comment by weierophinney** [comment]
Thanks, @codercms !
