### ISSUE TITLE
Replace ocramius/package-versions with composer/package-versions-deprecated 

### ISSUE THREAD

**Issue by boesing** [mezzio/mezzio-swoole#17]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

To support Composer 2 for all of the laminas packages, we have to replace `ocramius/package-versions` with composers fork `composer/package-versions-deprecated`.
The fork removed the PHP 7.4 limitation and thus provides Composer 2 support for PHP <7.4.

[composer/package-versions-deprecated](https://github.com/composer/package-versions-deprecated) is replacing `ocramius/package-versions` and thus can be used as a 1:1 replacement.

**Comment by Ocramius** [comment]
You can also keep the dependencies as they are, and get composer 2.x support if you are running with php 7.4+

**Comment by boesing** [comment]
Yes I know, but actually, we decided in the TSC that all laminas packages should support current PHP versions (which includes PHP 7.3 until december this year - or did I got something wrong?). Thus, we have to switch dependencies here. 🤷‍♂️
