### ISSUE TITLE
"file not found in package" error notice when using composer

### ISSUE THREAD

**Issue by demijohn** [mezzio/mezzio-swoole#51]
When updating mezzio-swoole package with composer (composer update) there is notice in console:
```
Skipped installation of bin bin/mezzio-swoole for package mezzio/mezzio-swoole: file not found in package
```

mezzio-swoole command was replaced by laminas command so "bin" section should be removed from composer.json:

```
"bin": [
        "bin/mezzio-swoole"
    ],
```

**Comment by weierophinney** [comment]
Fixed with #52
