### ISSUE TITLE
Update to dflydev/fig-cookies 3.0

### ISSUE THREAD

**Issue by acelaya** [mezzio/mezzio-swoole#54]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | no
| BC Break    | no

#### Summary

A new major version of `dflydev/fig-cookies` has been released, which adds support for PHP 8 (~among other things~).

Would you be open to update on this project? If so I can take care of it, I just need to know if you want to support both v2 and v3 at the same time.

**Comment by Ocramius** [comment]
@acelaya sure, send a patch, and it shall be reviewed :-)

**Comment by acelaya** [comment]
Just created the PR #55 

The change was actually quite small, as the only new thing in v3 is that they support PHP 8 now.
