### ISSUE TITLE
SwooleEmitter.php - SameSite=null

### ISSUE THREAD

**Issue by Bontah** [mezzio/mezzio-swoole#6]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.6

#### Summary

If there's a cookie in the response and the Cookie is missing the  'SameSite' directive then a fatal error will be thrown.

> PHP Fatal error:  Uncaught TypeError: Swoole\Http\Response::cookie() expects parameter 8 to be string, null given in /var/www/mezzio-test/vendor/mezzio/mezzio-swoole/src/SwooleEmitter.php:106

#### Current behavior

If there's a response with a cookie and no SameSite directive then the swoole process will just die

#### How to reproduce

I installed a clean and fresh instance of mezzio, configured the project to use swoole with these [instructions](https://docs.mezzio.dev/mezzio-swoole/v2/intro/), modified the HomePageHandler.php like this:
```
$response = new HtmlResponse($this->template->render('app::home-page', $data));
$cookie = 'CookieName=CookieValue; Expires=Wed, 01-Jul-2020 13:43:42 GMT; Path=/; Secure; HttpOnly;';
$response = $response->withHeader('Set-Cookie', $cookie);

return $response;
```

 and started it using php7.3 
`/usr/bin/php7.3  /mezzio-test/public/index.php`

i've fixed it by setting sameSite to an empty string instead of null:
`$sameSite = $cookie->getSameSite() ? substr($cookie->getSameSite()->asString(), 9) : '';
`

As for the SwooleEmitter.php tests: i don't know why phpunit doesn't have the same error. any hints for learning purposes would be nice.

#### Expected behavior

I'd expected to get a normal response with a Cookie

**Comment by pine3ree** [comment]
Hello @Bontah,  ...same here! ...same fix!
